spring.application.name=Task Manager
spring.datasource.url=jdbc:postgresql://localhost:5432/TaskManager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.schema=taskmanager