server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      schema: taskmanager
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
    redis:
      host: cache
      port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
    environment:
      RABBITMQ_ERLANG_COOKIE: "MySecretCookieValueForCluster"
