CREATE TABLE users
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) UNIQUE NOT NULL,
    email        VARCHAR(100) UNIQUE,
    phone_number VARCHAR(20) UNIQUE
);

CREATE TABLE tasks
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(50) NOT NULL,
    description VARCHAR(150),
    status      VARCHAR(50) NOT NULL
);

CREATE TABLE user_tasks
(
    user_id INT,
    task_id INT,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (task_id) REFERENCES tasks (id),
    PRIMARY KEY (user_id, task_id)
);
